"""Fix everything plase

Revision ID: 47e0ae55f505
Revises: 2b357bf3269a
Create Date: 2026-09-05 11:07:29.336891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e0ae55f505'
down_revision: Union[str, Sequence[str], None] = '2b357bf3269a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loves',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'power_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loves')
    # ### end Alembic commands ###
